name: Weekly Ice Report

on:
  schedule:
    # This will run the job every Monday at 23:00 UTC (11:00 PM UTC)
    - cron: '0 23 * * 1'
  workflow_dispatch:  # This allows manual triggering of the workflow

jobs:
  run_ice_report:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # If you have a requirements file
        # If you don't have a requirements file, list your dependencies here:
        # pip install package1 package2 package3

    - name: Run weekly ice report
      run: python weekly_ice_report.py

    # Optional: Add steps to handle the output, such as creating a commit, opening a PR, or sending an email
